import { BudgetCategory } from '@models/budget.models';

export const defaultCategories: BudgetCategory[] = [
  {
    id: 'income-general',
    name: 'General Income',
    type: 'income',
    isParent: true,
    values: {},
  },
  {
    id: 'income-sales',
    name: 'Sales',
    type: 'income',
    parentId: 'income-general',
    isParent: false,
    values: { '2025-01': 200, '2025-02': 400 },
  },
  {
    id: 'income-commission',
    name: 'Commission',
    type: 'income',
    parentId: 'income-general',
    isParent: false,
    values: { '2025-01': 0, '2025-02': 200 },
  },
  {
    id: 'income-general-placeholder',
    name: "Add a new 'General Income' Category",
    type: 'income',
    parentId: 'income-general',
    isParent: false,
    values: {},
    isPlaceholder: true,
  },
  {
    id: 'income-other',
    name: 'Other Income',
    type: 'income',
    isParent: true,
    values: {},
  },
  {
    id: 'income-training',
    name: 'Training',
    type: 'income',
    parentId: 'income-other',
    isParent: false,
    values: { '2025-01': 500, '2025-02': 550 },
  },
  {
    id: 'income-consulting',
    name: 'Consulting',
    type: 'income',
    parentId: 'income-other',
    isParent: false,
    values: { '2025-01': 500, '2025-02': 600 },
  },
  {
    id: 'income-other-placeholder',
    name: "Add New 'Other Income' category",
    type: 'income',
    parentId: 'income-other',
    isParent: false,
    values: {},
    isPlaceholder: true,
  },
  {
    id: 'income-new-parent-placeholder',
    name: 'Add New Parent Category',
    type: 'income',
    isParent: true,
    values: {},
    isPlaceholder: true,
  },
  {
    id: 'expense-operational',
    name: 'Operational Expenses',
    type: 'expense',
    isParent: true,
    values: {},
  },
  {
    id: 'expense-management',
    name: 'Management Fees',
    type: 'expense',
    parentId: 'expense-operational',
    isParent: false,
    values: { '2025-01': 100, '2025-02': 200 },
  },
  {
    id: 'expense-hosting',
    name: 'Cloud Hosting',
    type: 'expense',
    parentId: 'expense-operational',
    isParent: false,
    values: { '2025-01': 200, '2025-02': 400 },
  },
  {
    id: 'expense-operational-placeholder',
    name: "Add new 'Operational Expenses' category",
    type: 'expense',
    parentId: 'expense-operational',
    isParent: false,
    values: {},
    isPlaceholder: true,
  },
  {
    id: 'expense-salaries',
    name: 'Salaries & Wages',
    type: 'expense',
    isParent: true,
    values: {},
  },
  {
    id: 'expense-fulltime',
    name: 'Full Time Dev Salaries',
    type: 'expense',
    parentId: 'expense-salaries',
    isParent: false,
    values: { '2025-01': 100, '2025-02': 120 },
  },
  {
    id: 'expense-parttime',
    name: 'Part Time Dev Salaries',
    type: 'expense',
    parentId: 'expense-salaries',
    isParent: false,
    values: { '2025-01': 80, '2025-02': 80 },
  },
  {
    id: 'expense-remote',
    name: 'Remote Salaries',
    type: 'expense',
    parentId: 'expense-salaries',
    isParent: false,
    values: { '2025-01': 20, '2025-02': 0 },
  },
  {
    id: 'expense-salaries-placeholder',
    name: "Add new 'Sales and Wages' category",
    type: 'expense',
    parentId: 'expense-salaries',
    isParent: false,
    values: {},
    isPlaceholder: true,
  },
  {
    id: 'expense-new-parent-placeholder',
    name: 'Add new Parent Category',
    type: 'expense',
    isParent: true,
    values: {},
    isPlaceholder: true,
  },
];
